- name: Deploy MyApp
  hosts: localhost
  become: false

  tasks:

    - name: Run container
      docker_container:
        name: myapp
        image: myapp-image:latest
        ports:
          - "8081:80"
