- name: Deploy MyApp with Docker
  hosts: local
  become: true

  tasks:

    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Pull Docker image
      docker_image:
        name: myapp-image
        source: local

    - name: Run container
      docker_container:
        name: myapp
        image: myapp-image:latest
        state: started
        ports:
          - "8081:80"
